backend:
  name: github
  repo: your-username/sports-blog  # Replace with your repo name
  branch: main

media_folder: "uploads"  # Where images are stored
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Content", widget: "markdown" }
